version: '2'
services:
    elasticsearch:
      image: elasticsearch:5.4
      ports:
        - 9200:9200
      environment:
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - esdata1:/usr/share/elasticsearch/data
        - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

volumes:
  esdata1:
    driver: local
